import Golf6 from "../images/cars-big/golf6.jpg";
import AudiA1 from "../images/cars-big/audia1.jpg";
import Toyota from "../images/cars-big/toyotacamry.jpg";
import Bmw320 from "../images/cars-big/bmw320.jpg";
import Benz from "../images/cars-big/benz.jpg";
import Passat from "../images/cars-big/passatcc.jpg";

export const CAR_DATA = [
  [
    {
      name: "VW Golf 6",
      price: "5000",
      img: Golf6,
      model: "Golf 6",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Audi A1 S-Line",
      price: "7500",
      img: AudiA1,
      model: "Audi",
      mark: "A1",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Toyota Camry",
      price: "5000",
      img: Toyota,
      model: "Camry",
      mark: "Toyota",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Hybrid",
    },
  ],
  [
    {
      name: "BMW 320 ModernLine",
      price: "8000",
      img: Bmw320,
      model: "320",
      mark: "BMW",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Mercedes-Benz GLK",
      price: "8000",
      img: Benz,
      model: "Benz GLK",
      mark: "Mercedes",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "VW Passat CC",
      price: "6000",
      img: Passat,
      model: "Passat CC",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      "id": 1,
      "name": "Toyota Camry",
      "brand": "Toyota",
      "type": "Sedan",
      "fuel": "Petrol",
      "seats": 5,
      "pricePerDay": 2500,
      "location": "Mumbai, India",
      "image": "https://source.unsplash.com/400x300/?toyota,car",
      "rating": 4.5,
      "availability": true
    },
    {
      "id": 2,
      "name": "Honda Civic",
      "brand": "Honda",
      "type": "Sedan",
      "fuel": "Petrol",
      "seats": 5,
      "pricePerDay": 2200,
      "location": "Delhi, India",
      "image": "https://source.unsplash.com/400x300/?honda,civic",
      "rating": 4.7,
      "availability": true
    },
    {
      "id": 3,
      "name": "Ford Mustang",
      "brand": "Ford",
      "type": "Sports",
      "fuel": "Petrol",
      "seats": 4,
      "pricePerDay": 5000,
      "location": "Bangalore, India",
      "image": "https://source.unsplash.com/400x300/?ford,mustang",
      "rating": 4.8,
      "availability": false
    },
    {
      "id": 4,
      "name": "Tesla Model 3",
      "brand": "Tesla",
      "type": "Electric",
      "fuel": "Electric",
      "seats": 5,
      "pricePerDay": 4800,
      "location": "Hyderabad, India",
      "image": "https://source.unsplash.com/400x300/?tesla,car",
      "rating": 4.9,
      "availability": true
    },
    {
      "id": 5,
      "name": "BMW X5",
      "brand": "BMW",
      "type": "SUV",
      "fuel": "Diesel",
      "seats": 7,
      "pricePerDay": 4500,
      "location": "Chennai, India",
      "image": "https://source.unsplash.com/400x300/?bmw,x5",
      "rating": 4.6,
      "availability": true
    },
    {
      "id": 6,
      "name": "Mercedes-Benz GLC",
      "brand": "Mercedes",
      "type": "SUV",
      "fuel": "Petrol",
      "seats": 5,
      "pricePerDay": 4700,
      "location": "Kolkata, India",
      "image": "https://source.unsplash.com/400x300/?mercedes,glc",
      "rating": 4.7,
      "availability": true
    },
    {
      "id": 7,
      "name": "Hyundai Creta",
      "brand": "Hyundai",
      "type": "SUV",
      "fuel": "Diesel",
      "seats": 5,
      "pricePerDay": 2600,
      "location": "Pune, India",
      "image": "https://source.unsplash.com/400x300/?hyundai,creta",
      "rating": 4.5,
      "availability": true
    },
    {
      "id": 8,
      "name": "Kia Seltos",
      "brand": "Kia",
      "type": "SUV",
      "fuel": "Petrol",
      "seats": 5,
      "pricePerDay": 2700,
      "location": "Ahmedabad, India",
      "image": "https://source.unsplash.com/400x300/?kia,seltos",
      "rating": 4.6,
      "availability": true
    },
    {
      "id": 9,
      "name": "Maruti Suzuki Swift",
      "brand": "Maruti Suzuki",
      "type": "Hatchback",
      "fuel": "Petrol",
      "seats": 5,
      "pricePerDay": 2000,
      "location": "Jaipur, India",
      "image": "https://source.unsplash.com/400x300/?maruti,swift",
      "rating": 4.3,
      "availability": true
    },
    {
      "id": 10,
      "name": "Mahindra Thar",
      "brand": "Mahindra",
      "type": "Off-Road",
      "fuel": "Diesel",
      "seats": 4,
      "pricePerDay": 3500,
      "location": "Lucknow, India",
      "image": "https://source.unsplash.com/400x300/?mahindra,thar",
      "rating": 4.7,
      "availability": true
    },
    {
      "id": 11,
      "name": "Audi Q7",
      "brand": "Audi",
      "type": "Luxury SUV",
      "fuel": "Petrol",
      "seats": 7,
      "pricePerDay": 5000,
      "location": "Bhopal, India",
      "image": "https://source.unsplash.com/400x300/?audi,q7",
      "rating": 4.9,
      "availability": true
    },
    {
      "id": 12,
      "name": "Jaguar F-Pace",
      "brand": "Jaguar",
      "type": "Luxury SUV",
      "fuel": "Diesel",
      "seats": 5,
      "pricePerDay": 4900,
      "location": "Indore, India",
      "image": "https://source.unsplash.com/400x300/?jaguar,car",
      "rating": 4.8,
      "availability": true
    },
    {
      "id": 13,
      "name": "Skoda Octavia",
      "brand": "Skoda",
      "type": "Sedan",
      "fuel": "Petrol",
      "seats": 5,
      "pricePerDay": 2300,
      "location": "Nagpur, India",
      "image": "https://source.unsplash.com/400x300/?skoda,octavia",
      "rating": 4.4,
      "availability": true
    },
    {
      "id": 14,
      "name": "Tata Harrier",
      "brand": "Tata",
      "type": "SUV",
      "fuel": "Diesel",
      "seats": 5,
      "pricePerDay": 2800,
      "location": "Chandigarh, India",
      "image": "https://source.unsplash.com/400x300/?tata,harrier",
      "rating": 4.6,
      "availability": true
    },
    {
      "id": 15,
      "name": "Renault Kwid",
      "brand": "Renault",
      "type": "Hatchback",
      "fuel": "Petrol",
      "seats": 5,
      "pricePerDay": 2100,
      "location": "Mysore, India",
      "image": "https://source.unsplash.com/400x300/?renault,kwid",
      "rating": 4.2,
      "availability": true
    }
  ]
  
];
